### ISSUE TITLE
Panic on rust version 1.81

### ISSUE THREAD

**Issue by puffyCid** [ForensicRS/frnsc-prefetch#4]
:wave: Hello @SecSamDev , I wanted to open a small issue I recently encountered while using parts of this library. Specifically the huffman decompression code.

I am using the decompression [code](https://github.com/ForensicRS/frnsc-prefetch/blob/main/src/decompress/xpress_huff.rs) to help decompress Prefetch files.

Recently the sorting algorithm in Rust trait `Ord` changed in Rust version 1.81, as mentioned in the [release](https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html#new-sort-implementations) notes. 

Code that uses the `Ord` and `PartialOrd` traits now need to implement a `total order` sort otherwise Rust will panic with the message:
`user-provided comparison function does not correctly implement a total order`.

I was able to review and believe the issue is at:

```
symbol_info.sort_by(|a, b| {
        if a.length < b.length {
            return Ordering::Less;
        }

        if a.symbol < b.symbol {
            return Ordering::Less;
        }
        Ordering::Equal
    });
```

It looks like starting in version 1.81 both greater and less than comparisons need to be used. The code below no longer panics. 
```
symbol_info.sort_by(|a, b| {
        if a.length < b.length {
            return Ordering::Less;
        }
        if a.length > b.length {
            return Ordering::Greater;
        }

        if a.symbol < b.symbol {
            return Ordering::Less;
        }
        if a.symbol > b.symbol {
            return Ordering::Greater;
        }
        Ordering::Equal
    });
```

I can open a PR for the fix if you would like, otherwise will defer to you if you want to fix. 

Thanks again for the awesome library!

**Comment by SecSamDev** [comment]
Thanks for reporting. Feel free to make the pull request.

**Comment by SecSamDev** [comment]
Merged! Publishing new version
